name: web_scrapers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.7,3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dev dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements_dev.txt
    - name: Install
      run: |
          pip install -e src
    - name: Lint check with Black
      run: |
        black --check
    - name: Test with pytest
      run: |
        pytest
    - name: Static check with MyPy
      run: |
        ls -l
        mypy main test